# Generated by Django 5.0.6 on 2024-07-14 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bill',
            new_name='invoice',
        ),
    ]
