# Generated by Django 5.0.6 on 2024-07-15 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_rename_bill_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='qty_of_each_item',
            new_name='discount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='rate_of_each_item',
        ),
        migrations.AddField(
            model_name='invoice',
            name='transport',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='billedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('rate', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('item_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billed_item', to='bill.item')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='billed_items',
            field=models.ManyToManyField(related_name='invoices', to='bill.billeditem'),
        ),
    ]
