# Generated by Django 5.0.6 on 2024-07-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_rename_qty_of_each_item_invoice_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='billed_items',
            field=models.ManyToManyField(blank=True, null=True, related_name='invoices', to='bill.billeditem'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='grand_total',
            field=models.PositiveIntegerField(),
        ),
    ]
