# Generated by Django 5.0.6 on 2024-07-17 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0004_alter_invoice_billed_items_alter_invoice_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billeditem',
            old_name='total',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='s_gst',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='bill_from',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='bill_no',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='bill_to',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='billed_items',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='discount',
        ),
        migrations.AddField(
            model_name='invoice',
            name='cgst_amt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='grand_total_words',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bill.seller'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_items',
            field=models.ManyToManyField(to='bill.billeditem'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_no',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bill.buyer'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='other_charges',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sgst_amt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='taxable_amt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tgst_amt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seller',
            name='bank_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bill.bank'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='bal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='eway',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='grand_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='no_of_items',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='transport',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vehicle_no',
            field=models.CharField(max_length=15),
        ),
    ]
