# Generated by Django 5.0.6 on 2024-07-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0005_rename_total_billeditem_amount_remove_bank_s_gst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
