# Generated by Django 5.0.6 on 2024-07-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0006_invoice_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='tax',
            new_name='cgst',
        ),
        migrations.AddField(
            model_name='item',
            name='sgst',
            field=models.IntegerField(default=0),
        ),
    ]
