# Generated by Django 5.0.6 on 2024-07-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0008_alter_billeditem_amount_alter_billeditem_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billeditem',
            name='unit',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
