# Generated by Django 5.0.6 on 2024-07-18 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0009_billeditem_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='quantity',
            new_name='stock',
        ),
    ]
