# Generated by Django 5.0.6 on 2024-07-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0010_rename_quantity_item_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='aadhaar',
            field=models.BigIntegerField(default=0),
        ),
    ]
