# Generated by Django 5.0.6 on 2024-07-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0011_alter_employee_aadhaar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='aadhaar',
            field=models.CharField(max_length=15),
        ),
    ]
