# Generated by Django 5.0.6 on 2024-07-19 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0012_alter_employee_aadhaar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='bank_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bill.bank'),
        ),
    ]
