# Generated by Django 5.0.6 on 2024-07-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0013_alter_seller_bank_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='bank_details',
        ),
        migrations.AddField(
            model_name='seller',
            name='bank_ac_no',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='bank_branch',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='bank_ifsc',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='bank_name',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='bank',
        ),
    ]
