# Generated by Django 5.0.6 on 2024-07-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0014_remove_seller_bank_details_seller_bank_ac_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='bank_ifsc',
            field=models.CharField(max_length=20),
        ),
    ]
