# Generated by Django 5.0.6 on 2024-07-20 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0015_alter_seller_bank_ifsc'),
    ]

    operations = [
        migrations.CreateModel(
            name='entry_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_no', models.IntegerField(default=0)),
                ('transaction_type', models.CharField(max_length=15)),
                ('date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('mode', models.CharField(max_length=15)),
                ('note', models.CharField(max_length=200)),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bill.seller')),
            ],
        ),
    ]
