# Generated by Django 5.0.6 on 2024-07-20 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0017_entry_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry_stock',
            name='name',
        ),
        migrations.DeleteModel(
            name='entry_payment',
        ),
        migrations.DeleteModel(
            name='entry_stock',
        ),
    ]
