# Generated by Django 5.0.6 on 2024-07-20 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0018_remove_entry_stock_name_delete_entry_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='buyer_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_no', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('mode', models.CharField(max_length=10)),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bill.buyer')),
            ],
        ),
    ]
