# Generated by Django 5.0.6 on 2024-07-17 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gst', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('add', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('bal', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('empid', models.CharField(default=0, max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('add', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('bal', models.IntegerField(default=0)),
                ('aadhaar', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsn', models.CharField(max_length=7)),
                ('name', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('tax', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gst', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('add', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('bal', models.IntegerField(default=0)),
                ('bill_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='users_copy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='billedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('rate', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('item_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billed_item', to='demoapp.item')),
            ],
        ),
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bill_no', models.PositiveIntegerField(unique=True)),
                ('transport', models.CharField(blank=True, max_length=20)),
                ('no_of_items', models.PositiveIntegerField()),
                ('eway', models.CharField(max_length=20)),
                ('vehicle_no', models.CharField(max_length=10)),
                ('discount', models.PositiveIntegerField()),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('bill_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_to', to='demoapp.buyer')),
                ('billed_items', models.ManyToManyField(related_name='invoices', to='demoapp.billeditem')),
                ('bill_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_from', to='demoapp.seller')),
            ],
        ),
        migrations.CreateModel(
            name='bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ac_no', models.CharField(max_length=25)),
                ('branch', models.CharField(max_length=20)),
                ('ifsc', models.CharField(max_length=10)),
                ('s_gst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.seller')),
            ],
        ),
    ]
